require('plugins')
require('keymappings')
require('settings')
require('colorscheme')

-- Plugins
require('nv-compe')
require('nv-colorizer')
require('nv-nvimtree')
require('nv-treesitter')
require('nv-galaxyline')
require('nv-bufferline')
require('nv-gitsigns')
require('nv-autopairs')
require('nv-telescope')
require('nv-which-key')
require('nv-formattter')
-- require('nv-lint')

-- LSP
require('lsp')
require('lsp.lua-ls')
require('lsp.python-ls')
require('lsp.bash-ls')
require('lsp.go-ls')
require('lsp.clangd-ls')
require('lsp.json-ls')
require('lsp.vim-ls')
require('lsp.js-ts-ls')
require('lsp.html-ls')
require('lsp.css-ls')
